source 'https://github.com/winfredzen/WZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'WZSpecialKit_Example' do
  pod 'WZSpecialKit', :path => '../'

  target 'WZSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
